// Quiz questions data
const quizQuestions = [
  // Gen 1
  {
    category_name: "Gen 1",
    pokemon_count: 3,
    pokemon1_name: "bulbasaur",
    pokemon1_dialogue: "That's a Leech Seed merchant with a couple of leaves on its back, you cant be serious.",
    pokemon1_result_type: "no",
    pokemon2_name: "charmander",
    pokemon2_dialogue: "Let me guess, you also play Ryu in Street Fighter and listen to The Chainsmokers? Basic ass dude.",
    pokemon2_result_type: "understandable",
    pokemon3_name: "squirtle",
    pokemon3_dialogue: "I mean, cmon. Look at him. Can you believe he comes the owner of firearms later on?",
    pokemon3_result_type: "valid",
  },
  // Gen 2
  {
    category_name: "Gen 2",
    pokemon_count: 3,
    pokemon1_name: "chikorita",
    pokemon1_dialogue: "You a funny dude, you lie a lot.",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "cyndaquil",
    pokemon2_dialogue: "Its slim pickings, but due to recent leaked events, you definetly could've chosen better.",
    pokemon2_result_type: "understandable",
    pokemon3_name: "totodile",
    pokemon3_dialogue: "Great Movepool, even better evolution. (Why tf can he use Dragon Dance??)",
    pokemon3_result_type: "valid",
  },
  // Gen 3
  {
    category_name: "Gen 3",
    pokemon_count: 3,
    pokemon1_name: "treecko",
    pokemon1_dialogue: "Cool lil guy, but he aint really on anything tbh.",
    pokemon1_result_type: "no",
    pokemon2_name: "torchic",
    pokemon2_dialogue: "Say what you want, regardless of it being weak to 4 different types, its still flyer that you'll ever be.",
    pokemon2_result_type: "super_valid",
    pokemon3_name: "mudkip",
    pokemon3_dialogue: "Typeshit.",
    pokemon3_result_type: "valid",
  },
  // Gen 4
  {
    category_name: "Gen 4",
    pokemon_count: 3,
    pokemon1_name: "turtwig",
    pokemon1_dialogue: "How do you grow to have a PARK on your back, and still manage to have 85 Special Defense AND 4x weakness?? get this fraud of my screen.",
    pokemon1_result_type: "no",
    pokemon2_name: "chimchar",
    pokemon2_dialogue: "Lets be so honest with ourselves, this is PEAK evolution lines.",
    pokemon2_result_type: "valid",
    pokemon3_name: "piplup",
    pokemon3_dialogue: "Slow start, and even slower stats, but Empoleon do got that shit on.",
    pokemon3_result_type: "understandable",
  },
  // Gen 5
  {
    category_name: "Gen 5",
    pokemon_count: 3,
    pokemon1_name: "snivy",
    pokemon1_dialogue: "If pokemon could talk, this would the the racist one. Smarmy ass.",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "tepig",
    pokemon2_dialogue: "Pig with some underwear on wants to be Infernape/Blaziken/A good starter so bad. 🥀",
    pokemon2_result_type: "no",
    pokemon3_name: "oshawott",
    pokemon3_dialogue: "coo lil dude. :)",
    pokemon3_result_type: "valid",
  },
  // Gen 6
  {
    category_name: "Gen 6",
    pokemon_count: 3,
    pokemon1_name: "chespin",
    pokemon1_dialogue: "on YOUR soul this pokemon better than Froakie",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "fennekin",
    pokemon2_dialogue: "Big ass fox with a stick? Bro, i guess.",
    pokemon2_result_type: "understandable",
    pokemon3_name: "froakie",
    pokemon3_dialogue: "This isn't even fair how badly this dude solos, in stats and design. Its laughable.",
    pokemon3_result_type: "super_valid",
  },
  // Gen 7
  {
    category_name: "Gen 7",
    pokemon_count: 3,
    pokemon1_name: "rowlet",
    pokemon1_dialogue: "Sucks that Decidueye is hidden behind a meatball of a bird. Also his stats just suck.",
    pokemon1_result_type: "no",
    pokemon2_name: "litten",
    pokemon2_dialogue: "Wow, what a confusing evolution tree.",
    pokemon2_result_type: "valid",
    pokemon3_name: "popplio",
    pokemon3_dialogue: "I honestly forgot they exist.",
    pokemon3_result_type: "hell_no",
  },
  // Gen 8
  {
    category_name: "Gen 8",
    pokemon_count: 3,
    pokemon1_name: "grookey",
    pokemon1_dialogue: "Im biased to monkeys. I like monkeys. Also Rillaboom is just cool.",
    pokemon1_result_type: "super_valid",
    pokemon2_name: "scorbunny",
    pokemon2_dialogue: "I mean, they not Grookey, but ight. Also they colonized Greninja's ability, so it says a lot about you, doesn't it?",
    pokemon2_result_type: "understandable",
    pokemon3_name: "sobble",
    pokemon3_dialogue: "A brief gust of wind could kill this thing. This is Pokemon, not Make-A-Wish.",
    pokemon3_result_type: "hell_no",
  },
  // Gen 9
  {
    category_name: "Gen 9",
    pokemon_count: 3,
    pokemon1_name: "sprigatito",
    pokemon1_dialogue: "This isn't a haha weed thing, they're just cooler, and wayyy more viable.",
    pokemon1_result_type: "valid",
    pokemon2_name: "fuecoco",
    pokemon2_dialogue: "bro ew.",
    pokemon2_result_type: "no",
    pokemon3_name: "quaxly",
    pokemon3_dialogue: "You would have no idea this would turn out to be the most Brazilian Pokemon of all time.",
    pokemon3_result_type: "valid",
  },
  // Legendary Birds
  {
    category_name: "Legendary Birds",
    pokemon_count: 3,
    pokemon1_name: "articuno",
    pokemon1_dialogue: "I almost socked you just now.",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "zapdos",
    pokemon2_dialogue: "Lets be honest, he's just cooler.",
    pokemon2_result_type: "valid",
    pokemon3_name: "moltres",
    pokemon3_dialogue: "Team Valor still sucks btw.",
    pokemon3_result_type: "understandable",
  },
  // Legendary Beasts
  {
    category_name: "Legendary Beasts",
    pokemon_count: 3,
    pokemon1_name: "raikou",
    pokemon1_dialogue: "Design so mismatched, I thought it was a Digimon.",
    pokemon1_result_type: "no",
    pokemon2_name: "entei",
    pokemon2_dialogue: "I don't know why he look so prideful, he doesn't have much going for him.",
    pokemon2_result_type: "no",
    pokemon3_name: "suicune",
    pokemon3_dialogue: "Literally purifies water, and is a bad bitch (not like that, dont be weird).",
    pokemon3_result_type: "valid",
  },
  // Tower Duo
  {
    category_name: "Tower Duo",
    pokemon_count: 2,
    pokemon1_name: "lugia",
    pokemon1_dialogue: "Isn't really too different from Charizard, but I prefer them to Charizard because I refuse to be that basic of a human.",
    pokemon1_result_type: "valid",
    pokemon2_name: "ho-oh",
    pokemon2_dialogue: "Sorry Base Defense? Quad Weakness? I wish I could enjoy goofy Pokemon like you do.",
    pokemon2_result_type: "no",
  },
  // Legendary Giants (Regi Trio)
  {
    category_name: "Legendary Giants",
    pokemon_count: 5,
    pokemon1_name: "regirock",
    pokemon1_dialogue: "ALL THAT DEFENSE FOR FIVE WEAKNESSESS?! 5!  😭😂✌🏾",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "regice",
    pokemon2_dialogue: "Icicle version of Regirock",
    pokemon2_result_type: "no",
    pokemon3_name: "registeel",
    pokemon3_dialogue: "Least amount of weaknessess, and better overall design, as... basic as it is.",
    pokemon3_result_type: "valid",
    pokemon4_name: "regieleki",
    pokemon4_dialogue: "I hope you recieve the things that you deserve for choosing this.",
    pokemon4_result_type: "hell_no",
    pokemon5_name: "regidrago",
    pokemon5_dialogue: "Cool idea, terrible design. Who made this?",
    pokemon5_result_type: "understandable",
  },
  // Eon Duo
  {
    category_name: "Eon Duo",
    pokemon_count: 2,
    pokemon1_name: "latias",
    pokemon1_dialogue: "hell yeah girl, clock it.",
    pokemon1_result_type: "valid",
    pokemon2_name: "latios",
    pokemon2_dialogue: "My girlfriend is a misandrist, and I'm legally required to put down men unnecessarily at least once.",
    pokemon2_result_type: "no",
  },
  // Weather Trio
  {
    category_name: "Weather Trio",
    pokemon_count: 3,
    pokemon1_name: "kyogre",
    pokemon1_dialogue: "All he need to do is flood that sorry ass dinosaur, and he wins. Honestly, he sons him in aura alone.",
    pokemon1_result_type: "valid",
    pokemon2_name: "groudon",
    pokemon2_dialogue: "You gotta be 12.",
    pokemon2_result_type: "no",
    pokemon3_name: "rayquaza",
    pokemon3_dialogue: "Annoying Mountain Dew Can with 4 weaknesses. But i stil get it.",
    pokemon3_result_type: "understandable",
  },
  // Lake Guardians
  {
    category_name: "Lake Guardians",
    pokemon_count: 3,
    pokemon1_name: "uxie",
    pokemon1_dialogue: "Yeah, you could tell this the Being of Knowledge. Big ass head.",
    pokemon1_result_type: "understandable",
    pokemon2_name: "mesprit",
    pokemon2_dialogue: "Invented all emotions, including the negative ones. Who tf invents depression??",
    pokemon2_result_type: "no",
    pokemon3_name: "azelf",
    pokemon3_dialogue: "Humans would be nowhere without the gift of determination, so thanks cone head.",
    pokemon3_result_type: "valid",
  },
  // Creation Trio
  {
    category_name: "Creation Trio",
    pokemon_count: 3,
    pokemon1_name: "dialga",
    pokemon1_dialogue: "Really dope, actually. In design and concept. No notes.",
    pokemon1_result_type: "valid",
    pokemon2_name: "palkia",
    pokemon2_dialogue: "Why is the controller of space a water type??",
    pokemon2_result_type: "understandable",
    pokemon3_name: "giratina",
    pokemon3_dialogue: "I mean, cmon. LOOK AT HIM. AND HE CAN TRANSFORM. HE'S EDGY BUT I DON'T CARE HE'S FIRE",
    pokemon3_result_type: "super_valid",
  },
  // Lunar Duo
  {
    category_name: "Lunar Duo",
    pokemon_count: 2,
    pokemon1_name: "cresselia",
    pokemon1_dialogue: "You just be pickin whatever, huh?",
    pokemon1_result_type: "understandable",
    pokemon2_name: "darkrai",
    pokemon2_dialogue: "I wanted to be this guy so bad, he's so raw. It's like if Playboi Carti wasn't a deadbeat dad/overall terrible person and became a pokemon.",
    pokemon2_result_type: "valid",
  },
  // Swords of Justice
  {
    category_name: "Swords of Justice",
    pokemon_count: 4,
    pokemon1_name: "cobalion",
    pokemon1_dialogue: "I can't prove it just yet, but if he could speak english, he'd definetly be a podcast bro.",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "terrakion",
    pokemon2_dialogue: "Don't let their sturdy design make you think he'd keep you safe. He got 7 weaknesses. You better off with a Pidgey, lil bro.",
    pokemon2_result_type: "no",
    pokemon3_name: "virizion",
    pokemon3_dialogue: "4x weakness to Flying? A feather touches this thing, and it disintegrates.",
    pokemon3_result_type: "no",
    pokemon4_name: "keldeo",
    pokemon4_dialogue: "I don't know how he's managed to be the best option either, tbh. He just is statistically. Shoutout short people ig.",
    pokemon4_result_type: "valid",
  },
  // Forces of Nature
  {
    category_name: "Forces of Nature",
    pokemon_count: 3,
    pokemon1_name: "tornadus",
    pokemon1_dialogue: "Versatile, but I don't see why he needs to turn into a damn bird.",
    pokemon1_result_type: "understandable",
    pokemon2_name: "landorus",
    pokemon2_dialogue: "Overall, he's somehow the best one in terms of moves, but he gets to be a monkey, so I'll let it pass.",
    pokemon2_result_type: "understandable",
    pokemon3_name: "thundurus",
    pokemon3_dialogue: "Both Forms are cool, this is purely a design thing for me. Hence why Enamorus isn't included. If she was, you'd autofail the test for picking her.",
    pokemon3_result_type: "valid",
  },
  // Tao Trio
  {
    category_name: "Tao Trio",
    pokemon_count: 3,
    pokemon1_name: "reshiram",
    pokemon1_dialogue: "They look cooler than what they actually are, a slow and sorry fire type",
    pokemon1_result_type: "no",
    pokemon2_name: "zekrom",
    pokemon2_dialogue: "Great Offensively and the design is dope, I get it. Not really, but its cool.",
    pokemon2_result_type: "understandable",
    pokemon3_name: "kyurem",
    pokemon3_dialogue: "Covers everything the other two don't. Just sucks that he's the one pokemon that looks the most like a penis.",
    pokemon3_result_type: "understandable",
  },
  // Aura Trio
  {
    category_name: "Aura Trio",
    pokemon_count: 3,
    pokemon1_name: "xerneas",
    pokemon1_dialogue: "There go bambi yall, they think they're important now that they blue n shit.",
    pokemon1_result_type: "no",
    pokemon2_name: "yveltal",
    pokemon2_dialogue: "Clearly super evil and will absorb your life force, but the red is cool. :)",
    pokemon2_result_type: "valid",
    pokemon3_name: "zygarde",
    pokemon3_dialogue: "What a fumble man... looks cool but ain't nothing going on.",
    pokemon3_result_type: "no",
  },
  // Guardian Deities
  {
    category_name: "Guardian Deities",
    pokemon_count: 4,
    pokemon1_name: "tapu-koko",
    pokemon1_dialogue: "Looks like a dude named Zack. Eugh.",
    pokemon1_result_type: "hell_no",
    pokemon2_name: "tapu-lele",
    pokemon2_dialogue: "My girlfriend likes them, so I legally cant say anything bad. But just know that I know.",
    pokemon2_result_type: "valid",
    pokemon3_name: "tapu-bulu",
    pokemon3_dialogue: "Holds people down with plants and attacks them. Lazy ass.",
    pokemon3_result_type: "no",
    pokemon4_name: "tapu-fini",
    pokemon4_dialogue: "No notes, just a baddie.",
    pokemon4_result_type: "valid",
  },
];

module.exports = quizQuestions;
